services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - game-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - game-network

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - game-network

volumes:
  db_data:

networks:
  game-network:
    driver: bridge
