services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
      - game-server-1
      - game-server-2
    networks:
      - game-network

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - game-network

  game-server-1:
    container_name: game-server-1
    build:
      context: ./game-server
    ports:
      - "4001:4001"
    depends_on:
      - redis
    networks:
      - game-network

  game-server-2:
    container_name: game-server-2
    build:
      context: ./game-server
    ports:
      - "4002:4002"
    depends_on:
      - redis
    networks:
      - game-network

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - game-network

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - game-network

volumes:
  db_data:

networks:
  game-network:
    driver: bridge
